name: Android APK Build

on:
  push:
    tags:
      - '*'

  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Install Capacitor and Ionic CLI globally
        run: npm install -g @ionic/cli @capacitor/cli

      - name: Decode keystore
        run: echo ${{ secrets.ANDROID_KEYSTORE }} | base64 --decode > my-release-key.keystore

      - name: Create .env file
        run: |
          echo "STORE_FILE=../../DonkeysIsle2023.keystore" >> .env
          echo "STORE_PASSWORD=${{ secrets.STORE_PASSWORD }}" >> .env
          echo "KEY_ALIAS=${{ secrets.KEY_ALIAS }}" >> .env
          echo "KEY_PASSWORD=${{ secrets.KEY_PASSWORD }}" >> .env

      - name: Build web assets
        run: npm run build

      - name: Sync Capacitor plugins
        run: npx cap sync

      - name: Grant execute permission for Gradle wrapper
        run: chmod +x android/gradlew

      - name: Build Android APK
        env:
          KEYSTORE_ALIAS: ${{ secrets.KEYSTORE_ALIAS }}
          STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: npm run build:apk

      - name: Set TAG_NAME
        run: |
          echo "TAG_NAME=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: android/app/build/outputs/apk/release/*.apk

      - name: Download and install butler
        run: |
          curl -L -o butler.zip https://broth.itch.ovh/butler/linux-amd64/LATEST/archive/default
          unzip butler.zip
          chmod +x butler
          sudo mv butler /usr/local/bin

      - name: Push to Itch.io
        env:
          BUTLER_API_KEY: ${{ secrets.ITCHIO_API_KEY }}
        run: |
          butler push android/app/build/outputs/apk/release/*.apk donkey-isle/naelBirthday:android --userversion=${{ env.TAG_NAME }}
